In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('HistoricalAssetPricing.csv')

In [7]:
df

                           Asset     Date      Value
0   Bored Ape Average Sale Price  2021-05    1990.00
1   Bored Ape Average Sale Price  2021-06    7204.00
2   Bored Ape Average Sale Price  2021-07   13164.00
3   Bored Ape Average Sale Price  2021-08   86254.00
4   Bored Ape Average Sale Price  2021-09  165611.00
5   Bored Ape Average Sale Price  2021-10  168718.00
6   Bored Ape Average Sale Price  2021-11  218451.00
7   Bored Ape Average Sale Price  2021-12  258224.00
8   Bored Ape Average Sale Price  2022-01  285559.00
9   Bored Ape Average Sale Price  2022-02  310458.00
10  Bored Ape Average Sale Price  2022-03  294892.00
11  Bored Ape Average Sale Price  2022-04  412010.00
12  Bored Ape Average Sale Price  2022-05  283708.00
13  Bored Ape Average Sale Price  2022-06  130506.00
14  Bored Ape Average Sale Price  2022-07  133419.00
15  Bored Ape Average Sale Price  2022-08  150088.00
16  Bored Ape Average Sale Price  2022-09  120373.00
17  Bored Ape Average Sale Price  2022-10  112625.00
18                 Bitcoin Price  2021-05   57828.05
19                 Bitcoin Price  2021-06   36684.93
20                 Bitcoin Price  2021-07   33572.12
21                 Bitcoin Price  2021-08   39974.89
22                 Bitcoin Price  2021-09   48847.03
23                 Bitcoin Price  2021-10   48116.94
24                 Bitcoin Price  2021-11   61004.41
25                 Bitcoin Price  2021-12   57229.83
26                 Bitcoin Price  2022-01   47686.81
27                 Bitcoin Price  2022-02   38743.27
28                 Bitcoin Price  2022-03   44354.64
29                 Bitcoin Price  2022-04   46281.64
30                 Bitcoin Price  2022-05   38469.09
31                 Bitcoin Price  2022-06   29799.08
32                 Bitcoin Price  2022-07   19269.37
33                 Bitcoin Price  2022-08   23314.20
34                 Bitcoin Price  2022-09   20127.14
35                 Bitcoin Price  2022-10   19312.10
36                Ethereum price  2021-05    2772.84
37                Ethereum price  2021-06    2707.56
38                Ethereum price  2021-07    2274.40
39                Ethereum price  2021-08    2530.46
40                Ethereum price  2021-09    3430.76
41                Ethereum price  2021-10    3001.13
42                Ethereum price  2021-11    4288.22
43                Ethereum price  2021-12    4623.68
44                Ethereum price  2022-01    3683.05
45                Ethereum price  2022-02    2687.90
46                Ethereum price  2022-03    2919.78
47                Ethereum price  2022-04    3282.58
48                Ethereum price  2022-05    2729.99
49                Ethereum price  2022-06    1942.05
50                Ethereum price  2022-07    1068.32
51                Ethereum price  2022-08    1681.45
52                Ethereum price  2022-09    1553.76
53                Ethereum price  2022-10    1328.19

In [8]:
df['Value'] = df['Value'].apply(lambda x: round(np.log(x), 2))

In [9]:
df.to_csv('Cleaned_Asset_Prices.csv',index=False)